name: PCEAllyChecks
main: Aericio\PCEAllyChecks\PCEAllyChecks
version: 1.0.2
api: 3.11.2
load: POSTWORLD
author: Aericio
depend: [PiggyCustomEnchants]
softdepend: [FactionsPro, FactionsPE, Slapper, WorldGuard]
website: "https://github.com/Aericio/PCEAllyChecks/"