name: PCEAllyChecks
main: Aericio\PCEAllyChecks\PCEAllyChecks
version: 1.0.0
api: 3.11.2
load: POSTWORLD
author: Aericio
depend: [PiggyCustomEnchants]
softdepend: [FactionsPro, FactionsPE]
website: "https://github.com/Aericio/PCEAllyChecks/"